export function exportToPDF(student) {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();

    // Header
    doc.setFillColor(15, 23, 42); // bg-dark
    doc.rect(0, 0, 210, 40, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.text("DEBUG MASTER", 105, 25, { align: "center" });
    
    doc.setTextColor(30, 41, 59);
    doc.setFontSize(18);
    doc.text("Performance Certificate", 20, 55);

    // Content
    doc.setFontSize(12);
    doc.text(`Student Name: ${student.name}`, 20, 75);
    doc.text(`Email: ${student.email || 'N/A'}`, 20, 85);
    doc.text(`Role: Student`, 20, 95);
    doc.line(20, 100, 190, 100);

    doc.setFontSize(14);
    doc.text("Test Summary", 20, 115);
    doc.setFontSize(12);
    doc.text(`Score: ${student.score} / 100`, 20, 125);
    doc.text(`Percentage: ${student.percentage}%`, 20, 135);
    doc.text(`Status: ${student.testStatus}`, 20, 145);
    
    const malpracticeColor = student.malpracticeCount > 0 ? [239, 68, 68] : [34, 197, 94];
    doc.setTextColor(malpracticeColor[0], malpracticeColor[1], malpracticeColor[2]);
    doc.text(`Security Violations: ${student.malpracticeCount || 0}`, 20, 155);

    // Footer
    doc.setTextColor(100, 116, 139);
    doc.setFontSize(10);
    doc.text("Generated by Code Crafters Debugging Platform", 105, 280, { align: "center" });

    doc.save(`${student.name}_Result.pdf`);
}
